# Generated by Django 3.1.4 on 2020-12-08 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20201207_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='tasks',
        ),
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todoapp.custom_user'),
        ),
    ]
